### ISSUE TITLE
[BUG] Tracking not working

### ISSUE THREAD

**Issue by meap158** [ACK72/kavya-paperback-tracker#1]
Tracking doesnt seem to be working. It can find matching titles from kavita but upon clicking it will show the error below.

![image](https://user-images.githubusercontent.com/14327094/223015113-ecbe3b2e-8186-49dc-b6d0-1c952cef9c37.png)
![image](https://user-images.githubusercontent.com/14327094/223015123-45c824fd-72d0-41d1-9284-f0f3256e7486.png)

**Comment by ACK72** [comment]
Thanks for your report. I'll take a look for it.
Just in case, it does not affect tracking feature.

**Comment by ACK72** [comment]
Sorry for late. I've been busy in the meantime.
Kavya Tracker was updated to 1.0.0 and the issue was resolved.

**Comment by meap158** [comment]
Awesome. Thank you!
